# Generated by Django 4.0.3 on 2022-04-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0002_alter_super_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_type',
            name='type',
        ),
    ]
