# Generated by Django 4.0.3 on 2022-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0004_super_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super_type',
            name='type',
        ),
        migrations.AddField(
            model_name='super_type',
            name='hero_or_villian',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
