# Generated by Django 4.0.3 on 2022-04-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0005_remove_super_type_type_super_type_hero_or_villian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_type',
            old_name='hero_or_villian',
            new_name='type',
        ),
    ]
