# Generated by Django 4.0.3 on 2022-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='good_evil',
            new_name='super_type_id',
        ),
        migrations.AddField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
